blank_issues_enabled: false
contact_links:
  - name: 💬 General Support & Questions
    url: https://github.com/carlos-camara/vscode-gherkin-powertools/discussions
    about: Please ask questions and seek support in our Discussions forum.
